# Generated by Django 4.0.5 on 2022-06-18 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter a book genre(e.g science fiction,french poetry etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter the book natural languge (e.g English,french,japanese ect.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authour', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('isbn', models.CharField(help_text='13 character <a herf="http:isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('total_copies', models.IntegerField()),
                ('Available_copies', models.IntegerField()),
                ('Pic', models.ImageField(blank=True, null=True, upload_to='book_image')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this book', to='bookapp.genre')),
                ('languaage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookapp.language')),
            ],
        ),
    ]
